name: Daily Wine Scraper

on:
  # Dispara o workflow em um horário agendado (cron)
  schedule:
    # Executa todos os dias às 11:00 UTC (08:00 no horário de Brasília, GMT-3)
    # Formato: minuto hora dia mês dia-da-semana
    - cron: '0 11 * * *'
  
  # Permite que você execute este workflow manualmente pela aba Actions do GitHub
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a versão do Python que você está usando

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper script
        run: python main.py
        env:
          # Passa o Secret do GitHub para o script como uma variável de ambiente
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}

